// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqci1dYqgN7UsKD6iMbQcgYCq1VMHZR_Q',
    appId: '1:714159986760:web:c145c54838c29d8baa607d',
    messagingSenderId: '714159986760',
    projectId: 'balancecuisine',
    authDomain: 'balancecuisine.firebaseapp.com',
    storageBucket: 'balancecuisine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97DzBbNoawna0BtiWxT10xaRTt4WPfjE',
    appId: '1:714159986760:android:6127a2b32ace2809aa607d',
    messagingSenderId: '714159986760',
    projectId: 'balancecuisine',
    storageBucket: 'balancecuisine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNqhUARUSHqGeuU3HM2jD-NdCDn6HiCcc',
    appId: '1:714159986760:ios:91ae12d71f7ec8c5aa607d',
    messagingSenderId: '714159986760',
    projectId: 'balancecuisine',
    storageBucket: 'balancecuisine.firebasestorage.app',
    iosBundleId: 'com.example.balcuisine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNqhUARUSHqGeuU3HM2jD-NdCDn6HiCcc',
    appId: '1:714159986760:ios:91ae12d71f7ec8c5aa607d',
    messagingSenderId: '714159986760',
    projectId: 'balancecuisine',
    storageBucket: 'balancecuisine.firebasestorage.app',
    iosBundleId: 'com.example.balcuisine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqci1dYqgN7UsKD6iMbQcgYCq1VMHZR_Q',
    appId: '1:714159986760:web:e78b7c3f01fbebc8aa607d',
    messagingSenderId: '714159986760',
    projectId: 'balancecuisine',
    authDomain: 'balancecuisine.firebaseapp.com',
    storageBucket: 'balancecuisine.firebasestorage.app',
  );
}
